apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.deploymentName }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.client.component }}
  replicas: {{ .Values.client.replicas }}
  template:
    metadata:
      labels:
        component: {{ .Values.client.component }}
    spec:
      containers:
      - name: {{ .Values.client.containerName }}
        image: {{ .Values.client.front-image }}
        ports:
        - containerPort: {{ .Values.client.containerPort }}
        env:
        - name: {{ .Values.client.envName }}
          value: {{ .Values.client.envValue }}