apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend-service.name }}
spec:
  type: {{ .Values.backend-service.type }}
  selector:
    component: {{ .Values.backend-service.component }}
  ports:
    - port: {{ .Values.backend-service.port }}
      targetPort: {{ .Values.backend-service.targetport }}