apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
      - name: frontend
        image: mohamedswelam/client:11
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_PRODUCTION_IP
          value: backend-clusterip



apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.deploymentName }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.client.component }}
  replicas: {{ .Values.client.replicas }}
  template:
    metadata:
      labels:
        component: {{ .Values.client.component }}
    spec:
      containers:
      - name: {{ .Values.client.containerName }}
        image: {{ .Values.client.image }}
        ports:
        - containerPort: {{ .Values.client.containerPort }}
        env:
        - name: {{ .Values.client.envName }}
          value: {{ .Values.client.envValue }}