apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend-service.name }}
spec:
  type: {{ .Values.frontend-service.servicetype }}
  selector:
    component: {{ .Values.frontend-service.component }}
  ports:
  - port: {{ .Values.frontend-service.port }}
    targetPort: {{ .Values.frontend-service.targetport }}
    nodePort: {{ .Values.frontend-service.nodeport }
