apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo-service.name }}
spec:
  type: {{ .Values.mongo-service.type }}
  selector:
    component: {{ .Values.mongo-service.component }}
  ports:
  - port: 27017
