apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.name }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.mongo.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.mongo.component }}
    spec:
      volumes:
      - name: {{ .Values.mongo.volumename }}
        persistentVolumeClaim:
          claimName: mongo-presistent-volume-claim
      containers:
      - name: {{ .Values.mongo.containername }}
        image: {{ .Values.mongo.containerimage }}
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: {{ .Values.mongo.mountname }}
          mountPath: {{ .Values.mongo.mountpath }}
        env:
        - name: {{ .Values.mongo.envname1 }}
          value: {{ .Values.mongo.envvalue1 }}
        - name: {{ .Values.mongo.envname2 }}
          value: {{ .Values.mongo.envvalue2 }}
        - name: {{ .Values.mongo.envname3 }}
          valueFrom:
              secretKeyRef:
                name: mongo-root-password
                key: MONGO_INITDB_ROOT_PASSWORD