apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: sonarqube
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it-support@example.com
    privateKeySecretRef:
      name: sonarqube
    http01: {}
